const express = require("express");
const mongoose = require("mongoose");
const cors = require("cors");
const dotenv = require("dotenv");
const { Resend } = require("resend");

// --- NEW FILE HANDLING IMPORTS ---
const multer = require("multer");
const cloudinary = require("cloudinary").v2;
const { CloudinaryStorage } = require("multer-storage-cloudinary");

// Import your Blueprints
const Contact = require("./models/Contact");
const Career = require("./models/Career"); // <-- New Blueprint

dotenv.config();
const app = express();

app.use(cors());
app.use(express.json());

// Connect to MongoDB
mongoose
  .connect(process.env.MONGO_URI)
  .then(() => console.log("✅ Successfully connected to MongoDB Atlas!"))
  .catch((error) => console.log("❌ MongoDB Connection Error:", error.message));

// --- CLOUDINARY CONFIGURATION ---
cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
});

// --- MULTER SETUP (The Toll Booth for Resumes) ---
const storage = new CloudinaryStorage({
  cloudinary: cloudinary,
  params: {
    folder: "JMD_Resumes", // Creates a folder in your Cloudinary account
    allowedFormats: ["pdf", "doc", "docx"],
  },
});
const upload = multer({ storage: storage });

// --- EMAIL API SETUP (Bypasses Render Firewall) ---
const resend = new Resend(process.env.RESEND_API_KEY);

// ==========================================
//                 API ROUTES
// ==========================================

app.get("/", (req, res) => {
  res.send("JMD Security Backend is officially running! 🚀");
});

// --- 1. CONTACT FORM ROUTE ---
app.post("/api/contact", async (req, res) => {
  try {
    const { name, phone, email, service, message } = req.body;

    const newInquiry = new Contact({ name, phone, email, service, message });
    await newInquiry.save();
    console.log("📬 Contact saved to database!");

    // Send Email Notification via Resend API
    await resend.emails.send({
      from: `"${name} (Website Lead)" <onboarding@resend.dev>`, // Required for Resend free tier
      to: process.env.EMAIL_USER,
      reply_to: email,
      subject: `🚨 NEW CLIENT LEAD: ${name} needs ${service}`,
      text: `You have a new lead from the website!\n\nName: ${name}\nPhone: ${phone}\nEmail: ${email}\nService Required: ${service}\nMessage:\n${message}`,
    });
    console.log("📧 Contact email sent successfully via Resend!");

    res
      .status(201)
      .json({ success: true, message: "Inquiry received successfully!" });
  } catch (error) {
    console.error("Error saving contact:", error);
    res
      .status(500)
      .json({ success: false, message: "Server error. Please try again." });
  }
});

// --- 2. CAREERS FORM ROUTE (NEW!) ---
// Notice the "upload.single('resume')" middleware. It intercepts the file before running the code!
app.post("/api/career", upload.single("resume"), async (req, res) => {
  try {
    const { fullName, email, phone, position, experience } = req.body;

    // req.file.path is the secure URL generated by Cloudinary
    const resumeUrl = req.file ? req.file.path : "No resume uploaded";

    // 1. Save to Database
    const newApplicant = new Career({
      fullName,
      email,
      phone,
      position,
      experience,
      resumeUrl, // We save the link, not the heavy file!
    });

    await newApplicant.save();
    console.log("📄 Job Applicant saved to database!");

    // 2. Send Email Notification via Resend API
    await resend.emails.send({
      from: `"${fullName} (Job Applicant)" <onboarding@resend.dev>`, // Required for Resend free tier
      to: process.env.EMAIL_USER,
      reply_to: email,
      subject: `👔 NEW JOB APPLICANT: ${fullName} for ${position}`,
      text: `You have a new job application!\n\nName: ${fullName}\nPhone: ${phone}\nEmail: ${email}\nPosition: ${position}\nExperience: ${experience} Years\n\n📄 View Resume: ${resumeUrl}`,
    });
    console.log("📧 Applicant email sent successfully via Resend!");

    res
      .status(201)
      .json({ success: true, message: "Application submitted successfully!" });
  } catch (error) {
    console.error("Error saving career application:", error);
    res
      .status(500)
      .json({ success: false, message: "Server error. Please try again." });
  }
});

// ==========================================
//               START SERVER
// ==========================================
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => {
  console.log(`🚀 Server is awake and listening on http://localhost:${PORT}`);
});
